use_frameworks!

target 'LEGO-NavigationController_Example' do
  pod 'LEGO-NavigationController', :path => '../'

  target 'LEGO-NavigationController_Tests' do
    inherit! :search_paths

    
  end
end
